version: '3.0'

services:
  flask-server:
    image: findz-flask-server:latest
    container_name: flask-server
    volumes:
      - ./static/:/app/static/
      - ./templates:/app/templates
      - ./webXR/index.html:/app/templates/webXR.html
      - ./database:/app/database
      - ./app.py:/app/app.py
      - ./Examples/circle_coordinates.py:/app/Examples/circle_coordinates.py
      # - findz-volume:/app/persistent/
    restart: unless-stopped
    
  cloudflare-tunnel:
    image: cloudflare/cloudflared:latest
    container_name: cloudtunnel
    command: tunnel --no-autoupdate run --token ${CLOUD_TOKEN}
    restart: unless-stopped

# volumes:
#   findz-volume: