version: '3.0'

services:
  flask-server:
    image: findz-flask-server:latest
    container_name: flask-server
    volumes:
      - ./static/:/app/static/:ro
      - ./templates:/app/templates:ro
      - ./webXR/index.html:/app/templates/webXR.html:ro
      - ./database:/app/database:ro
      - ./app.py:/app/app.py:ro
    
  cloudflare-tunnel:
    image: cloudflare/cloudflared:latest
    container_name: cloudtunnel
    command: tunnel --no-autoupdate run --token ${CLOUD_TOKEN}